version: '3.8'

services:
  app:
    build: .
    ports:
      - "5000-5003:5000"
    volumes:
      - ./models:/app/models
      - ./uploads:/app/uploads
    environment:
      - TF_ENABLE_ONEDNN_OPTS=0
    restart: unless-stopped